spring.application.name=tickethub

# Activate the 'local' profile by default for local development.
# This will make Spring also load properties from application-local.properties
spring.profiles.active=local

# General Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings (Optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
